version: '3.8'

services:
  user-api:
    build: user-microservice
    volumes:
      - ./user-microservice:/opt/jboss/wildfly/standalone/deployments
    ports:
      - 8080:8080
      - 8787:8787
    command: /opt/jboss/wildfly/bin/standalone.sh -b 0.0.0.0 -bmanagement 0.0.0.0 --debug *:8787
    depends_on:
      - pgdb

  inventory-api:
    build: inventory-microservice
    volumes:
      - ./inventory-microservice:/opt/jboss/wildfly/standalone/deployments
    ports:
      - 8081:8080
      - 8788:8787
    command: /opt/jboss/wildfly/bin/standalone.sh -b 0.0.0.0 -bmanagement 0.0.0.0 --debug *:8787
    depends_on:
      - pgdb

  pgdb:
    image: postgres
    container_name: pgdb
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./ms-client/dist/ms-client/:/usr/share/nginx/html
      - ./ms-client/nginx.conf:/etc/nginx/nginx.conf
    command: [ nginx, '-g', 'daemon off;' ]

#  ms-client:
#    build: ms-client
#    volumes:
#      - ./ms-client:/usr/src/app/ms-client
#      - /usr/src/app/ms-client/node_modules
#    ports:
#      - 4200:4200
#    depends_on:
#      - user-api
#      - inventory-api

